### ISSUE TITLE
MQTTの証明書対応

### ISSUE THREAD

**Issue by skisair** [skisair/gps-recorder#79]

**Comment by skisair** [comment]
```
data_processor_1  | topic:devices/${device_id}/messages/events/?data_id=${data_id}
data_processor_1  | Traceback (most recent call last):
data_processor_1  |   File "/opt/data_processor/data_processor.py", line 174, in <module>
data_processor_1  |     data_processor.run()
data_processor_1  |   File "/opt/data_processor/data_processor.py", line 81, in run
data_processor_1  |     self.mqtt_client.connect(mqtt_host, port=mqtt_port, keepalive=keep_alive)
data_processor_1  |   File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 941, in connect
data_processor_1  |     return self.reconnect()
data_processor_1  |   File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1104, in reconnect
data_processor_1  |     sock.do_handshake()
data_processor_1  |   File "/usr/local/lib/python3.9/ssl.py", line 1309, in do_handshake
data_processor_1  |     self._sslobj.do_handshake()
data_processor_1  | ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)
```
